### ISSUE TITLE
Not working on Youtube

### ISSUE THREAD

**Issue by albertopasqualetto** [polywock/pipUnblocker#6]
I am using this in Microsoft Edge, but it doesn't work on Youtube (not TV), is this function intended? Or am I doing something wrong? What should I see/do?
Thanks

Edit: I am on version 0.1 and I see the extension should be on version 0.3, but I can't find any update in Microsoft Store

**Comment by polywock** [comment]
Youtube TV uses a Feature-Policy header to block PIP functionality. As far as I'm aware, Youtube TV is the only website that does this. They claim it's because of legal reasons they had to block it. 

Youtube.com doesn't block PiP so this extension isn't needed. PiP Unblocker is a very niche extension.

**Comment by albertopasqualetto** [comment]
Ok thanks for your answer!

Il Lun 12 Apr 2021, 19:58 polywock ***@***.***> ha scritto:
