### ISSUE TITLE
Doesn't work much where

### ISSUE THREAD

**Issue by Ved-un** [polywock/pipUnblocker#8]
Doesn't work much where,
for example here https://www.ontvtime.ru/live/russia1-tv.html

And that doesn't work either - **removeDisablePiPAttribute**

Only your **Global Speed** works, but unnecessary functions like speed control annoy me personally)

For some reason, the built-in PiP in Firefox works on all sites, but not in Chrome.

**Comment by polywock** [comment]
> https://www.ontvtime.ru/live/russia1-tv.html

It's working for me without any third party tool. Are you using a particular player? Maybe the flash one?  


https://user-images.githubusercontent.com/31208859/118782852-83a40a80-b85c-11eb-99a2-a8aa4825473c.mov

**Comment by Ved-un** [comment]
No, I do not use third party players

Here is one TV channel and everything works on it - https://www.ontvtime.ru/live/1tv.html

https://i.imgur.com/gTFy60R.png

but this one does not work and there is not even an icon - https://www.ontvtime.ru/live/russia1-tv.html

https://i.imgur.com/Q9oiU6f.png

**Comment by Ved-un** [comment]
Ah ... it is clear why it works for you
you have the addon enabled - **global speed** ... )))

With this addon it works for me too, but my question was about this particular addon - **pipUnblocker**

**Comment by Ved-un** [comment]
Okay,
nothing too scary ...

I will use Firefox until the Edge learns how to do PiP correctly  ) 

Firefox does it on all sites, - out of the box - https://i.imgur.com/1gfnnsi.png

**Comment by polywock** [comment]
Weird, that channel seems to work for me as well. With or without global speed. 
By the way, no need for imgur, you could just drag and drop your image. 

![works](https://user-images.githubusercontent.com/31208859/118791057-58bdb480-b864-11eb-8eaa-e686f6b5181d.png)

**Comment by Ved-un** [comment]
This only works for me with your addon **Global Speed**
and without media control enabled in flags - I don't need media control. 


![](https://i.imgur.com/xNL235c.png)




p.s. I have **Linux** and **Edge-dev** maybe because of this...

**Comment by Ved-un** [comment]
I'll go and give you a star for **Global Speed** )

**Comment by Ved-un** [comment]
It is necessary to insert some code from Global Speed into this addon so that the PiP would work the same way ...

only I don't know - which one and where   ))

**Comment by polywock** [comment]
Thanks for the star. 

I think i figured it out. The [removeDisablePiPAttribute](https://github.com/polywock/removeDisablePiPAttribute) bookmarklet only runs on the top frame. The video looks to be inside an iframe. I think the userscript alternative should work.  

1. Install [Tampermonkey](https://microsoftedge.microsoft.com/addons/detail/tampermonkey/iikmkjmpaadaobahmlepeloendndfphd) 
2. Install [the userscript](https://greasyfork.org/en/scripts/426660-remove-pip-disable-attributes).

**Comment by Ved-un** [comment]
I don't have Windows - only Linux
but for him there is not yet the Edge of the release ...
Only Beta and Developer ... right now I'll try to install Beta Edge and see how it is ...

Maybe I bothered you in vain and I have a problem?

**Comment by Ved-un** [comment]
> * Install [Tampermonkey](https://microsoftedge.microsoft.com/addons/detail/tampermonkey/iikmkjmpaadaobahmlepeloendndfphd)
> 
> * Install [the userscript](https://greasyfork.org/en/scripts/426660-remove-pip-disable-attributes).

I would not like to install Tampermonkey because of this ...

I have a lighter addon **Custom Style Script**
https://mybrowseraddon.com/custom-style-script.html
and yours **userscript** does not work with it either. ((

**Comment by polywock** [comment]
I'll have to give up. To make Global Speed more tolerable. 

1. In the Global Speed options page, remove all default hotkeys. 

![ad](https://user-images.githubusercontent.com/31208859/118799287-8b6bab00-b86c-11eb-9444-3961481f1670.png)

2. Right click the Global Speed option and click on "Manage extensions". Change the Site Access to "On Specific Sites". Add these two sites. 

`https://www.ontvtime.ru/*`

`*://*.mediavitrina.ru/*`

![ag](https://user-images.githubusercontent.com/31208859/118800605-18fbca80-b86e-11eb-90fd-76d4f00a131f.png)

![af](https://user-images.githubusercontent.com/31208859/118800056-79d6d300-b86d-11eb-9060-aac17d83897e.png)


Why mediavitrina.ru as well? Just in case, since it looks like the video is loaded from that website based on your screenshot. If it stops working, change it back to all sites, refresh your ontvtime.ru page, and check the URL Global Speed shows for that video, and add it as well. 


![ae](https://user-images.githubusercontent.com/31208859/118799751-164ca580-b86d-11eb-97a9-9495224a756f.png)

3. Move Global Speed icon to the menu so it's not always visible. 

![ab](https://user-images.githubusercontent.com/31208859/118800258-b99dba80-b86d-11eb-8c70-a4a711f9caa5.png)

![ac](https://user-images.githubusercontent.com/31208859/118800293-c02c3200-b86d-11eb-9c6f-ff34dcec3076.png)
